Repository A3Antistasi/antistasiofficial, pull requests merged in 2018-05, with the labels that each got.

#326 Add sqf linter on push
  .circleci/config.yml
  AntistasiOfficial.Altis/AI/airCA.sqf
  AntistasiOfficial.Altis/JeroenArsenal/JNA/fn_arsenal.sqf
  AntistasiOfficial.Altis/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
  AntistasiOfficial.Altis/Scripts/UPSMON/COMMON/vehicles/fnc/UPSMON_assignasgunner.sqf
  AntistasiOfficial.Altis/Scripts/UPSMON/MODULES/ARTILLERY/fnc/UPSMON_selectartillery.sqf
  bin/config_validator.py
  bin/sqf_validator.py
Labels: Ready

#328 VCOM tweaking (beta)
  AntistasiOfficial.Altis/VCOMAI/functions/VCOMAI_DefaultSettings.sqf
Labels: WIP

#313 Supply system by wurzel0701
  AntistasiOfficial.Altis/CREATE/createSupplyBox.sqf
  AntistasiOfficial.Altis/CREATE/createSupplyGroup.sqf
  AntistasiOfficial.Altis/Functions/fn_SpawnCiviGetSupplies.sqf
  AntistasiOfficial.Altis/Functions/fn_addActionMP.sqf
  AntistasiOfficial.Altis/Functions/fn_changeCitySupply.sqf
  AntistasiOfficial.Altis/Functions/fn_changeCitySupport.sqf
  AntistasiOfficial.Altis/Functions/fn_getHighSupplies.sqf
  AntistasiOfficial.Altis/Functions/functionList.hpp
  AntistasiOfficial.Altis/JeroenArsenal/JNL/fn_logistics_init.sqf
  AntistasiOfficial.Altis/Missions/missionrequest.sqf
  AntistasiOfficial.Altis/Save/fn_loadGame.sqf
  AntistasiOfficial.Altis/Save/fn_saveFunctions.sqf
  AntistasiOfficial.Altis/Save/fn_saveGame.sqf
  AntistasiOfficial.Altis/cityinfo.sqf
  AntistasiOfficial.Altis/distancias3.sqf
  AntistasiOfficial.Altis/initFuncs.sqf
  AntistasiOfficial.Altis/initVar.sqf
  AntistasiOfficial.Altis/initZones.sqf
  AntistasiOfficial.Altis/moveHQ.sqf
  AntistasiOfficial.Altis/resourcecheck.sqf
Labels: help wanted, need testing

#340 Undercover cargo
  AntistasiOfficial.Altis/undercover.sqf
Labels: Ready

#341 hotfix supply group not deleted
  AntistasiOfficial.Altis/CREATE/createSupplyGroup.sqf
  AntistasiOfficial.Altis/Functions/fn_despawnUnits.sqf
  AntistasiOfficial.Altis/Stringtable.xml
  AntistasiOfficial.Altis/distancias3.sqf
Labels: Ready

#342 Store vehicle's ACE cargo into garage when the vehicle is garaged (#332)
  AntistasiOfficial.Altis/JeroenArsenal/JNG/fn_garage_garageVehicle.sqf
Labels: need testing
